name: build_cloud

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_cloud:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - run: git clone https://github.com/abap2UI5/builder && cd builder && npm i
    - run: rm -rf setup/* && cp -r ../setup/cloud/* setup
    - run: npm run clone && npm run rename && npm run abaplint
    - run: cp -r dist/* .. && rm -rf ../builder

    - name: Commit Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add *
        git commit -m "Downport changes"

    - name: Switch to Branch cloud
      run: git checkout -b cloud

    - name: Push Changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: cloud
        force: true
